include:
  - https://gitlab.com/ubports/porting/community-ports/halium-generic-adaptation-build-tools/-/raw/main/gsi-port-ci.yml

variables:
  ROOTFS_URL: "https://ci.ubports.com/job/focal-hybris-rootfs-arm64/job/master/lastSuccessfulBuild/artifact/ubuntu-touch-android9plus-rootfs-arm64.tar.gz"
  OTA_CHANNEL: "20.04/arm64/android9plus/stable"

image: ubuntu:20.04

build:
  rules:
   - when: never

flashable:
  rules:
   - when: never

devel-flashable:
  rules:
   - when: never

build-android12-5.4:
  tags: [ubports]
  extends: build
  before_script:
    - ln -sf deviceinfo-android12-5.4 deviceinfo
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"

build-android12-5.10:
  tags: [ubports]
  extends: build
  before_script:
    - ln -sf deviceinfo-android12-5.10 deviceinfo
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"

devel-flashable-android12-5.4:
  extends: [devel-flashable]
  needs: [build-android12-5.4]
  before_script:
    - ln -sf deviceinfo-android12-5.4 deviceinfo
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"

devel-flashable-android12-5.10:
  extends: [devel-flashable]
  needs: [build-android12-5.10]
  before_script:
    - ln -sf deviceinfo-android12-5.10 deviceinfo
  rules:
   - if: $CI_PIPELINE_SOURCE == "push"
